### ISSUE TITLE
Install Error neovim 6 nightly

### ISSUE THREAD

**Issue by Trid-collab** [Furkanzmc/firvish.nvim#4]
I was impressed by your talk in Vimconf2021 and installed firvish on my neovim nightly latest build.
But I getting the following error upon installation. Am I missing anything here.  The site doesn't have any install instructions. I am using Packer

![image](https://user-images.githubusercontent.com/61322708/139684437-98282895-5d5e-44ce-9f44-37737b84d49e.png)

**Comment by Furkanzmc** [comment]
> I was impressed by your talk in Vimconf2021 and installed firvish on my neovim nightly latest build.

Hey! Thanks so much! I appreciate it. I'm glad people were not thrown off by the technical problems I was having. 😅

> But I getting the following error upon installation. Am I missing anything here. The site doesn't have any install instructions. I am using Packer

Sorry for that! I haven't been able to put that much effort into making this publicly consumable. I grew it bit by it and forgot to fix/change things here and there. I just pushed a new commit. Can you latest master and let me know if you still see the same error? I also added installation instructions and mentioned that (optional) plugin.

Thanks for trying out the plugin.

**Comment by Trid-collab** [comment]
I have updated firvish to the latest release and have installed options.nvim, but even then I am still getting the following error message when I am starting vim. Do I need to do something like `require "options".setup{}` 
I have presently done nothing of the sort as I was hoping it would work out of the box

![image](https://user-images.githubusercontent.com/61322708/139789898-a0a11034-7369-4776-a13c-6511df594e94.png)

**Comment by Furkanzmc** [comment]
You can ignore that warning message.

I guess I should remove it. It seems to be causing confusion. The plug-in should work now.

**Comment by Trid-collab** [comment]
Do I need to still install options.nvim

**Comment by Furkanzmc** [comment]
You shouldn't need that plugin. I'll remove the warning message later today. Sorry about that!
